package com.sahernandezz.nexusai.multimodal;

import com.sahernandezz.nexusai.auth.UserDirectory;
import com.sahernandezz.nexusai.files.FileService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.MediaType;
import org.springframework.http.codec.multipart.FilePart;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.server.RouterFunction;
import org.springframework.web.reactive.function.server.RouterFunctions;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

@Slf4j
@Component
@RequiredArgsConstructor
public class MultimodalHandler {

    private final MultimodalService service;
    private final FileService fileService;
    private final UserDirectory userDirectory;

    private static final String DATA_URL_PREFIX = "data:";
    private static final WebClient HTTP = WebClient.builder().build();

    /** POST /api/multimodal/describe — image → text */
    public Mono<ServerResponse> describeImage(ServerRequest request) {
        return request.multipartData().flatMap(parts -> {
            var filePart = (FilePart) parts.getFirst("file");
            String instruction = parts.containsKey("instruction")
                    ? String.valueOf(parts.getFirst("instruction"))
                    : null;
            String mimeType = request.headers().firstHeader("X-Content-Type");
            if (mimeType == null)
                mimeType = "image/jpeg";

            final String mt = mimeType;
            return saveTemp(filePart).flatMap(path -> {
                var resource = new org.springframework.core.io.FileSystemResource(path.toFile());
                return service.describeImage(resource, mt, instruction)
                        .flatMap(desc -> ServerResponse.ok()
                                .contentType(MediaType.APPLICATION_JSON)
                                .bodyValue(Map.of("description", desc)))
                        .doFinally(s -> silentDelete(path));
            });
        });
    }

    /**
     * POST /api/multimodal/generate — text → image (DALL-E 3 / gpt-image-1).
     *
     * Always persists the generated image to MinIO via {@link FileService} so
     * the chat can reference it by stable {@code refId} after a reload (DALL-E
     * URLs expire in ~1h; base64 data URLs blow up the chat store JSON). The
     * response includes both:
     * <ul>
     *   <li>{@code refId} — UUID for the {@code attachments} table</li>
     *   <li>{@code url}   — convenience GET path the frontend can also use</li>
     * </ul>
     */
    public Mono<ServerResponse> generateImage(ServerRequest request) {
        return request.bodyToMono(Map.class).flatMap(body -> {
            String prompt = (String) body.get("prompt");
            String size = (String) body.getOrDefault("size", "1024x1024");
            String quality = (String) body.getOrDefault("quality", "standard");
            String model = (String) body.getOrDefault("model", null);
            UUID conversationId = parseConversationId(body.get("conversationId"));

            return userDirectory.currentUserId().flatMap(userId ->
                service.generateImage(prompt, size, quality, model)
                        .flatMap(urlOrData -> persistGenerated(urlOrData, userId, conversationId))
                        .flatMap(payload -> ServerResponse.ok()
                                .contentType(MediaType.APPLICATION_JSON)
                                .bodyValue(payload)));
        });
    }

    /**
     * Fetches the generated bytes (either by HTTP from a hosted URL, or by
     * decoding a base64 data: URL) and stores them in MinIO so the asset
     * outlives the OpenAI URL TTL and the browser session.
     */
    private Mono<Map<String, Object>> persistGenerated(String urlOrData, UUID userId, UUID conversationId) {
        Mono<byte[]> bytesMono;
        if (urlOrData == null || urlOrData.isBlank()) {
            return Mono.error(new IllegalStateException("Image generation returned empty payload"));
        }
        if (urlOrData.startsWith(DATA_URL_PREFIX)) {
            int comma = urlOrData.indexOf(',');
            String b64 = comma > 0 ? urlOrData.substring(comma + 1) : urlOrData.substring(DATA_URL_PREFIX.length());
            bytesMono = Mono.fromCallable(() -> Base64.getDecoder().decode(b64))
                    .subscribeOn(Schedulers.boundedElastic());
        } else if (urlOrData.startsWith("http://") || urlOrData.startsWith("https://")) {
            bytesMono = HTTP.get().uri(urlOrData)
                    .retrieve()
                    .bodyToMono(byte[].class);
        } else {
            // Fallback (e.g. service returned a plain message instead of an image — preserve old behavior)
            Map<String, Object> raw = new HashMap<>();
            raw.put("url", urlOrData);
            return Mono.just(raw);
        }

        String filename = "generated-" + Instant.now().toEpochMilli() + ".png";
        return bytesMono.flatMap(bytes -> fileService.storeBytes(
                        userId, conversationId, bytes, filename, "image/png", "generated"))
                .map(att -> {
                    Map<String, Object> out = new HashMap<>();
                    out.put("refId", att.id().toString());
                    out.put("refKind", "attachment");
                    out.put("url", "/api/files/" + att.id());
                    out.put("filename", att.filename());
                    out.put("contentType", att.contentType());
                    out.put("size", att.sizeBytes());
                    return out;
                })
                .doOnError(ex -> log.error("[Multimodal] persistGenerated failed: {}", ex.getMessage(), ex));
    }

    private static UUID parseConversationId(Object raw) {
        if (raw == null) return null;
        try { return UUID.fromString(String.valueOf(raw)); } catch (Exception e) { return null; }
    }

    private Mono<Path> saveTemp(FilePart part) {
        return Mono.fromCallable(() -> Files.createTempFile("nexusai-mm-", "-" + part.filename()))
                .flatMap(tmp -> part.transferTo(tmp).thenReturn(tmp));
    }

    private void silentDelete(Path p) {
        try {
            Files.deleteIfExists(p);
        } catch (IOException ignored) {
        }
    }
}

@Configuration(proxyBeanMethods = false)
@RequiredArgsConstructor
class MultimodalRouter {
    @Bean
    RouterFunction<ServerResponse> multimodalRoutes(MultimodalHandler handler) {
        return RouterFunctions.route()
                .POST("/api/multimodal/describe", handler::describeImage)
                .POST("/api/multimodal/generate", handler::generateImage)
                .build();
    }
}
