package com.sahernandezz.nexusai.conversations;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sahernandezz.nexusai.conversations.dto.ConversationDto;
import com.sahernandezz.nexusai.conversations.dto.MessageDto;
import io.r2dbc.postgresql.codec.Json;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Owns the persistent chat history. Each conversation belongs to one user;
 * each message has a deterministic {@code clientId} (UUID generated by the
 * browser) so the frontend can upsert without worrying about retries.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ConversationService {

    private final ConversationRepository convRepo;
    private final MessageRepository msgRepo;
    private final DatabaseClient db;
    private final ObjectMapper objectMapper;

    // ── Conversations ────────────────────────────────────────────────────────

    public Flux<ConversationDto> listForUser(UUID userId) {
        return convRepo.findAllByUserId(userId)
                .map(this::toDtoNoMessages);
    }

    public Mono<ConversationDto> getWithMessages(UUID conversationId, UUID userId) {
        return convRepo.findByIdAndUserId(conversationId, userId)
                .flatMap(conv -> msgRepo.findByConversationOrderedFrontend(conv.id())
                        .map(this::toMessageDto)
                        .collectList()
                        .map(msgs -> toDto(conv, msgs)));
    }

    /**
     * Idempotent create. The frontend passes its locally-generated UUID so
     * the backend can use the same id throughout — no id-swap, no race
     * window where messages target a non-existent server id. If the row
     * already exists it's returned as-is (concurrent creates from multiple
     * tabs collapse to a single row).
     */
    public Mono<ConversationDto> create(UUID requestedId, UUID userId, String title, String model) {
        UUID id = requestedId != null ? requestedId : UUID.randomUUID();
        String resolvedTitle = title != null ? title : "New Chat";
        return db.sql("""
                INSERT INTO conversations (id, user_id, title, model, created_at, updated_at)
                VALUES (:id, :user, :title, :model, NOW(), NOW())
                ON CONFLICT (id) DO NOTHING
                """)
                .bind("id", id)
                .bind("user", userId)
                .bind("title", resolvedTitle)
                .bind("model", model == null ? "" : model) // can't bind null without bindNull
                .fetch().rowsUpdated()
                .then(convRepo.findByIdAndUserId(id, userId))
                .map(this::toDtoNoMessages);
    }

    public Mono<ConversationDto> rename(UUID conversationId, UUID userId, String newTitle) {
        return convRepo.findByIdAndUserId(conversationId, userId)
                .flatMap(conv -> {
                    ConversationEntity updated = new ConversationEntity(
                            conv.id(), conv.userId(),
                            newTitle != null && !newTitle.isBlank() ? newTitle : conv.title(),
                            conv.model(), conv.createdAt(), Instant.now(), false);
                    return convRepo.save(updated).map(this::toDtoNoMessages);
                });
    }

    public Mono<Void> delete(UUID conversationId, UUID userId) {
        return convRepo.deleteByIdAndUserId(conversationId, userId);
    }

    // ── Messages ─────────────────────────────────────────────────────────────

    /**
     * Upsert a message keyed by {@code clientId}. Used by every frontend
     * write (initial insert, streaming-update of the assistant content,
     * RAG action state changes).
     */
    public Mono<MessageDto> upsertMessage(UUID conversationId, UUID userId, MessageDto dto) {
        if (dto.clientId() == null)
            return Mono.error(new IllegalArgumentException("clientId is required"));

        // Auto-create the conversation row if it doesn't exist yet — this
        // tolerates the race where the frontend fires the message PUT before
        // the explicit POST /api/conversations has completed (or if that POST
        // got lost). Idempotent thanks to ON CONFLICT (id) DO NOTHING.
        return ensureConversationExists(conversationId, userId)
                .then(convRepo.findByIdAndUserId(conversationId, userId))
                .switchIfEmpty(Mono.error(new IllegalStateException("conversation not found")))
                .flatMap(conv -> {
                    Json attachments = jsonOrNull(dto.attachments());
                    Json ragAction = jsonOrNull(dto.ragAction());
                    var spec = db.sql("""
                            INSERT INTO chat_messages
                                (conversation_id, session_id, role, content, message_index,
                                 attachments, rag_action, cached, cache_layer, model,
                                 client_id, created_at)
                            VALUES (:conv, :session, :role, :content, :idx,
                                    :attachments::jsonb, :rag::jsonb, :cached, :layer, :model,
                                    :client, NOW())
                            ON CONFLICT (client_id) WHERE client_id IS NOT NULL DO UPDATE SET
                                content      = EXCLUDED.content,
                                attachments  = EXCLUDED.attachments,
                                rag_action   = EXCLUDED.rag_action,
                                cached       = EXCLUDED.cached,
                                cache_layer  = EXCLUDED.cache_layer,
                                model        = EXCLUDED.model,
                                message_index = EXCLUDED.message_index
                            """)
                            .bind("conv", conversationId)
                            .bind("session", conversationId.toString())
                            .bind("role", dto.role() != null ? dto.role() : "user")
                            .bind("content", dto.content() != null ? dto.content() : "")
                            .bind("idx", dto.messageIndex() != null ? dto.messageIndex() : 0)
                            .bind("cached", Boolean.TRUE.equals(dto.cached()))
                            .bind("client", dto.clientId());
                    spec = attachments != null
                            ? spec.bind("attachments", attachments.asString())
                            : spec.bindNull("attachments", String.class);
                    spec = ragAction != null
                            ? spec.bind("rag", ragAction.asString())
                            : spec.bindNull("rag", String.class);
                    spec = dto.cacheLayer() != null
                            ? spec.bind("layer", dto.cacheLayer())
                            : spec.bindNull("layer", String.class);
                    spec = dto.model() != null
                            ? spec.bind("model", dto.model())
                            : spec.bindNull("model", String.class);
                    return spec.fetch().rowsUpdated()
                            .then(touchConversation(conv))
                            .thenReturn(dto);
                });
    }

    public Mono<Void> deleteMessage(UUID conversationId, UUID userId, UUID clientId) {
        return convRepo.findByIdAndUserId(conversationId, userId)
                .flatMap(conv -> msgRepo.deleteByClientId(conversationId, clientId)
                        .then(touchConversation(conv)));
    }

    private Mono<Void> touchConversation(ConversationEntity conv) {
        ConversationEntity bumped = new ConversationEntity(
                conv.id(), conv.userId(), conv.title(), conv.model(),
                conv.createdAt(), Instant.now(), false);
        return convRepo.save(bumped).then();
    }

    /**
     * Ensures a conversations row exists for the given (id, userId) pair.
     * Idempotent — does nothing if it's already there. Used to recover from
     * the race where the frontend sends a message PUT before the explicit
     * POST /api/conversations has landed.
     */
    private Mono<Void> ensureConversationExists(UUID conversationId, UUID userId) {
        return db.sql("""
                INSERT INTO conversations (id, user_id, title, created_at, updated_at)
                VALUES (:id, :user, 'New Chat', NOW(), NOW())
                ON CONFLICT (id) DO NOTHING
                """)
                .bind("id", conversationId)
                .bind("user", userId)
                .fetch().rowsUpdated()
                .then();
    }

    // ── Mapping helpers ─────────────────────────────────────────────────────

    private ConversationDto toDtoNoMessages(ConversationEntity e) {
        return new ConversationDto(e.id(), e.title(), e.model(), e.createdAt(), e.updatedAt(), null);
    }

    private ConversationDto toDto(ConversationEntity e, List<MessageDto> messages) {
        return new ConversationDto(e.id(), e.title(), e.model(), e.createdAt(), e.updatedAt(), messages);
    }

    private MessageDto toMessageDto(MessageEntity e) {
        return new MessageDto(
                e.clientId(),
                e.role(),
                e.content(),
                e.messageIndex(),
                parse(e.attachments()),
                parse(e.ragAction()),
                e.cached(),
                e.cacheLayer(),
                e.model(),
                e.createdAt());
    }

    private Json jsonOrNull(JsonNode node) {
        if (node == null || node.isNull())
            return null;
        try {
            return Json.of(objectMapper.writeValueAsString(node));
        } catch (Exception e) {
            log.warn("[ConversationService] failed to serialize JSONB: {}", e.getMessage());
            return null;
        }
    }

    private JsonNode parse(Json json) {
        if (json == null)
            return null;
        try {
            return objectMapper.readTree(json.asString());
        } catch (Exception e) {
            return null;
        }
    }
}
