package com.sahernandezz.nexusai.conversations.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.JsonNode;

import java.time.Instant;
import java.util.UUID;

/**
 * Message wire shape — mirrors the React {@code ChatMessage} type.
 *
 * {@code clientId} is generated by the browser (crypto.randomUUID) and used as
 * the upsert key, so retries and replays don't duplicate rows.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MessageDto(
        UUID clientId,
        String role,           // user | assistant | system
        String content,
        Integer messageIndex,
        JsonNode attachments,  // raw JSON array
        JsonNode ragAction,    // raw JSON object
        Boolean cached,
        String cacheLayer,
        String model,
        Instant createdAt
) {}
