Args = \
  --enable-url-protocols=http,https \
  --install-exit-handlers \
  -H:+AddAllCharsets \
  --initialize-at-run-time=\
    io.netty.channel.DefaultFileRegion,\
    io.netty.channel.epoll.Epoll,\
    io.netty.channel.kqueue.KQueue,\
    io.netty.handler.ssl.OpenSsl,\
    io.netty.internal.tcnative.SSL \
  --initialize-at-build-time=\
    ch.qos.logback,\
    org.slf4j.LoggerFactory,\
    org.slf4j.helpers

